/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_androwarn_sampleapplication_NativeCode */

#ifndef _Included_com_androwarn_sampleapplication_NativeCode
#define _Included_com_androwarn_sampleapplication_NativeCode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_androwarn_sampleapplication_NativeCode
 * Method:    NativeMethod
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_androwarn_sampleapplication_NativeCode_NativeMethod
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
